Feature/wfdm 753
bcgov/nr-bcws-opensearch pull request #50
Opened 2023-05-08 23:38 UTC by vivid-fxie

2023-05-09 21:49 UTC, vivid-fxie commented
Will need to use java 11 or 17 as lambda runtime in aws side in order for new open search client to compile

2023-05-10 17:12 UTC, vivid-fxie commented
Will update this pr with java 17 as runtime

2023-05-10 19:23 UTC, vivid-fxie commented
I was not able run lambda locally with java 17, using java 11 works. So I updated runtime to java 11.

2023-05-11 17:23 UTC, dhlevi requested changes

2023-05-11 17:23 UTC, dhlevi commented on wfdm-file-index-service/src/main/java/ca/bc/gov/nrs/wfdm/wfdm_file_index_service/OpenSearchRESTClient.java
> +			throw new RuntimeException("JSON?????", e);
Not an appropriate Exception message. CLean it up to be clear on what error occured.

2023-05-11 17:30 UTC, vivid-fxie commented on wfdm-file-index-service/src/main/java/ca/bc/gov/nrs/wfdm/wfdm_file_index_service/OpenSearchRESTClient.java
> +	private static String units = "BKMGTPEZY";
It is used in the api before for converting file size back to bytes from human readable. It was hard coded before.

2023-05-11 17:38 UTC, dhlevi commented
Looks like there's a conflict to clear up as well

2023-05-11 18:06 UTC, merged